disabled_rules:
- trailing_whitespace
- comment_spacing
# - line_length
# - identifier_name
- void_function_in_ternary
- colon
- empty_enum_arguments
- orphaned_doc_comment
 
opt_in_rules:
- empty_count
- empty_string
 
excluded:
- Pods
- CocoaLumberjack

nesting:
  type_level:
    warning: 3
    error: 5
  statement_level:
    warning: 3
    error: 5

identifier_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1
 
line_length:
  warning: 570
  error: 700
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
 
function_body_length:
  warning: 300
  error: 500
 
function_parameter_count:
  warning: 6
  error: 8
 
type_body_length:
  warning: 500
  error: 700
  ignore_comment_only_lines: true
 
file_length:
  warning: 1000
  error: 1500
  ignore_comment_only_lines: true
 
cyclomatic_complexity:
  warning: 15
  error: 25
 
reporter: "xcode"
